---
title: "lecture notes markdown"
output: html_document
date: "2023-09-21"
---

input data
```{r}
library(tidyverse)
options(tibble.print_min = 3)
litters_data = read_csv("./data/FAS_litters.csv",
                        col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
                     col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)

filter(pups_data, sex == 1)
```


```{r}
drop_na(litters_data)
drop_na(litters_data, gd0_weight)
```


```{r}
arrange(litters_data, group, gd0_weight)
```


#9.26

```{r}
library(tidyverse)
pulse_df = 
  haven::read_sas("./data/public_pulse_data.sas7bdat") |>
  janitor::clean_names()

pulse_df
```
```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    values_to = "bdi")

pulse_tidy_data
```
convert to long dataset
```{r}
pulse_tidy_data = 
  pivot_longer(
    pulse_df, 
    bdi_score_bl:bdi_score_12m,
    names_to = "visit", 
    names_prefix = "bdi_score_",
    values_to = "bdi")

pulse_tidy_data
```
##bind rows
covert to wide dataset
```{r}
litters_wide = 
  read_csv("./data/FAS_litters.csv") |>
  janitor::clean_names() |>
  select(litter_number, ends_with("weight")) |> 
  pivot_longer(
    gd0_weight:gd18_weight,
    names_to = "gd", 
    values_to = "weight") |> 
  mutate(
    gd = case_match(
      gd,
      "gd0_weight"  ~ 0,
      "gd18_weight" ~ 18
    )) 

litters_wide
```
less smart way is `replace`

## LoTR

```{r}
fellowship_ring = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "B3:D6") |>
  mutate(movie = "fellowship_ring")

two_towers = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "F3:H6") |>
  mutate(movie = "two_towers")

return_king = 
  readxl::read_excel("./data/LotR_Words.xlsx", range = "J3:L6") |>
  mutate(movie = "return_king")

fellowship_ring
two_towers
return_king

lotr_df = 
  bind_rows(fellowship_ring, two_towers, return_king)
lotr_df
```

```{r}
lotr_tidy = 
  bind_rows(fellowship_ring, two_towers, return_king) |>
  janitor::clean_names() |>
  pivot_longer(
    female:male,
    names_to = "gender", 
    values_to = "words") |>
  mutate(race = str_to_lower(race)) |> 
  select(movie, everything()) 

lotr_tidy
```


```{r}
analysis_result = 
  tibble(
    group = c("treatment", "treatment", "placebo", "placebo"),
    time = c("pre", "post", "pre", "post"),
    mean = c(4, 8, 3.5, 4)
  )

analysis_result
```

```{r}
pivot_wider(
  analysis_result, 
  names_from = "time", 
  values_from = "mean")
```
`seperate(group, into = c("dose", "day_of_treatment")), 3`

```{r}
pups_df = read_csv("data/FAS_pups.csv")|>
  janitor::clean_names()|>
  mutate(
    sex = case_match(
      sex,
      1 ~ "male",
      2 ~ "female"
    )
  )

pups_df
```

# 9.28
```{r}
library(tidyverse)
library(ggridges)
```
```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USC00519397 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax))
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point()
```
```{r}
weather_df |>
  ggplot(aes(x = tmin, y = tmax)) + 
  geom_point()
```
```{r}
ggp_weather = 
  weather_df |>
  ggplot(aes(x = tmin, y = tmax)) 

ggp_weather + geom_point()

```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name))
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax)) + 
  geom_point(aes(color = name), alpha = .3) +
  geom_smooth(se = FALSE)
```
```{r}
ggplot(weather_df, aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .3) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```
```{r}
ggplot(weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point(aes(size = prcp), alpha = .5) +
  geom_smooth(se = FALSE) + 
  facet_grid(. ~ name)
```


